$(document).ready(function(){

	var sites = [ 'Google',
								'Facebook',
								'YouTube',
								'Wikipedia',
								'LinkedIn',
								'AirBNB',
								'Urban Dictionary',
								'Twitter',
								'Instagram',
								'SnapChat',
								'Amazon',
								'WordPress',
								'eBay',
								'Tumblr',
								'Pinterest',
								'PayPal',
								'Craigslist',
								'IMDB',
								'Stack Overflow',
								'Flickr',
								'CNN',
								'TechCrunch',
								'Mashable',
								'Reddit',
								'Digg',
								'Mapquest',
								'Netflix',
								'Vimeo',
								'New York Times',
								'Dropbox',
								'Evernote',
								'Angry Birds',
								'HootSuite',
								'SlideShare',
								'Yelp',
								'Mailchimp',
								'StumbleUpon',
								'Weather Channel',
								'Etsy',
								'GitHub',
								'E*Trade',
								'Spotify',
								'Uber',
								'Nest',
								'Bitcoin'];

	var groups = ['cat lovers',
								'dog lovers',
								'homeschoolers',
								'furries',
								'watch repairmen',
								'math teachers',
								'gym rats',
								'popcorn enthusiasts',
								'surfers',
								'architects',
								'lawyers',
								'doctors',
								'ice sculptors',
								'truck drivers',
								'submarine cooks',
								'bounty hunters',
								'human statues',
								'sperm donors',
								'crab fisherman',
								'waterslide testers',
								'elevator mechanics',
								'Barbie dress designers',
								'wig makers',
								'cruise ship entertainers',
								'lifeguards',
								'phone psychics',
								'chicken sexers',
								'golfers',
								'window washers',
								'zookeepers',
								'basketweavers',
								'used car salesmen',
								'Apple Store employees',
								'crocodile wranglers',
								'pet detectives',
								'rodeo clowns',
								'worm farmers',
								'recruiters',
								'developers',
								'designers',
								'accountants',
								'rocket scientists',
								'photographers',
								'authors',
								'movie stars',
								'landscapers',
								'guitar players',
								'bartenders',
								'fishmongers',
								'bloggers'];

	$('#go').click(function(){
		generate();
	});
	generate();

	function generate() {
		var siteNumber = Math.floor(Math.random()*sites.length);
		var groupNumber = Math.floor(Math.random()*groups.length);
		$('#site').html(sites[siteNumber]);
		$('#group').html(groups[groupNumber]);
	}

});